apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  labels:
    app: db
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
    
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
           - name: PGDATA
             value: /var/lib/postgresql/data/pgdata
          envFrom:
           - secretRef:
                name: db-secret

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
